wallpaper {
	monitor = DP-1
	path = /home/kirk/Pictures/earthrise.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/kirk/Pictures/earthrise.jpg
	fit_mode = cover
}

splash = false
